name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        java: ['16']
    name: Tests (Java ${{ matrix.java }})

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK {{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
        cache: maven

    - name: Install MiniZinc
      run: |
           wget https://github.com/MiniZinc/MiniZincIDE/releases/download/2.3.2/MiniZincIDE-2.3.2-bundle-linux-x86_64.tgz -O minizinc.tgz
           tar -xzvf minizinc.tgz
           rm minizinc.tgz

    - name: Build with Maven
      run: mvn clean --batch-mode --update-snapshots verify

    - name: Release
      uses: qcastel/github-actions-maven-release@master
      env:
        JAVA_HOME: /usr/lib/jvm/java-16-openjdk/
      with:
        git-release-bot-name: "bot-idhub"
        git-release-bot-email: "bot@idhub.io"

        maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"
        maven-servers: '[{"id": "serverId1", "username": "username", "password": "password", "privateKey": "test", "passphrase": "testes"}, {"id": "serverId2", "username": "username2", "password": "password2"}]'
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
